@startuml
abstract class Mediator {}

class ConcreteMediator {
    colleagues:HashMap
}

abstract class Colleague {}

class ConcreteColleague {
    ConcreteColleague()
}

ConcreteMediator --|> Mediator
ConcreteColleague --|> Colleague

Mediator - Colleague

ConcreteMediator o-- Colleague

ConcreteColleague ..> Mediator
@enduml

@startuml
abstract class Mediator {}


class ConcreteMediator {
    colleagues:HashMap
    getMessage():void
}

abstract class Colleague {
    sendMessage():void
    getMediator():Mediator
}

class TV {}

class Alarm {}

class CoffeeMachine {}

class Curtains {}

class Client {}

ConcreteMediator --|> Mediator

TV --|> Colleague
Alarm --|> Colleague
CoffeeMachine --|> Colleague
Curtains --|> Colleague

Mediator -- Colleague

Colleague --o ConcreteMediator

TV ..> Mediator
Alarm ..> Mediator
CoffeeMachine ..> Mediator
Curtains .right.> Mediator

Client .right.> Mediator
Client .right.> Colleague
@enduml
